build:
  publish: build-output/
  command: npm run build
plugins:
  - package: '@netlify/plugin-lighthouse'
context:
  production:
    publish: output/
    command: make publish
    environment:
      NODE_VERSION: 14.15.3
  deploy-preview:
    publish: dist/
    environment:
      NOT_PRIVATE_ITEM: not so secret
  branch-deploy:
    command: echo branch
    environment:
      NODE_ENV: development
  staging:
    command: echo 'staging'
    base: staging
  feat/branch:
    command: echo 'special branch'
    base: branch
redirects:
  - from: /*
    to: '/blog/:splat'
  - from: /old-path
    to: /new-path
    status: 302
    force: true
    query:
      id: ':id'
    conditions:
      Language:
        - en
    headers:
      X-From: Netlify
      X-Api-Key: some-api-key-string
  - from: /gated-path
    status: 200
    conditions:
      Role:
        - admin
    force: true
  - from: /*
    to: /index.html
    status: 200
headers:
functions:
  directory: functions/
