name: development workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout repo'
        uses: actions/checkout@v3

      - name: 'run tests'
        run: |
          npm ci
          npm run serve &
          npm test

      - name: 'run build'
        run: |
          npm run build

      - name: 'Deploy after tests succeeded'
        id: deployment
        uses: netlify/actions/cli@master
        with: 
          args: deploy --dir=dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}